"""Feature-parity inventory: every Desktop popup, menu, and git op is present."""

from __future__ import annotations

from github_desktop.models import BannerType, PopupType, PreferencesTab, RepositorySettingsTab
from github_desktop.git import ops as git_ops
from github_desktop.ui import dialogs
from github_desktop.ui.window import MainWindow


REQUIRED_GIT_FUNCS = [
    "get_status",
    "create_commit",
    "get_working_directory_diff",
    "get_working_directory_lines",
    "get_blob_lines",
    "get_blob_contents",
    "get_commit_diff",
    "ensure_relative_path",
    "diff_from_raw_diff_output",
    "get_commits",
    "get_changeset_data",
    "parse_raw_log_with_numstat",
    "get_commit_range_changed_files",
    "get_commit_range_diff",
    "get_branches",
    "create_branch",
    "rename_branch",
    "delete_local_branch",
    "checkout_branch",
    "clone_repository",
    "init_repository",
    "fetch",
    "pull",
    "push",
    "merge",
    "rebase",
    "cherry_pick",
    "stash_push",
    "stash_pop",
    "create_tag",
    "discard_paths",
    "discard_changes_from_selection",
    "undo_commit",
    "reset",
    "revert",
    "squash_commits",
    "reorder_commits",
    "read_gitignore",
    "read_gitignore_at_root",
    "write_gitignore",
    "save_gitignore",
    "format_gitignore_contents",
    "lfs_track",
    "get_submodules",
    "get_repository_kind",
    "add_safe_directory",
    "stage_files",
    "apply_patch_to_index",
    "determine_mergeability",
    "get_commits_between",
    "get_ahead_behind_range",
    "get_boolean_config_value",
    "warn_about_remote_commits",
    "install_global_lfs_filters",
    "install_lfs_hooks",
    "abort_squash_merge",
    "format_patch",
    "parse_trailers",
    "merge_trailers",
    "format_commit_message",
    "get_global_config_path",
    "is_using_lfs",
    "is_tracked_by_lfs",
    "get_recent_branches",
    "get_files_with_conflict_markers",
    "parse_credential",
    "format_credential",
    "get_branch_checkouts",
    "fetch_refspec",
    "get_binary_paths",
    "get_cherry_pick_snapshot",
    "get_rebase_snapshot",
    "get_last_desktop_stash_entry_for_branch",
    "move_stash_entry",
    "fetch_tags_to_push",
    "fast_forward_branches",
    "get_branches_differing_from_upstream",
    "get_merged_branches",
    "get_index_changes",
    "check_patch",
    "get_files_diff_text",
    "get_branch_merge_base_diff",
    "get_branch_merge_base_changed_files",
    "get_branches_pointed_at",
    "get_authors",
    "get_author_identity",
    "get_symbolic_ref",
    "prune_forked_remotes",
    "find_forked_remotes_to_prune",
    "create_desktop_stash_entry",
    "discard_working_files",
    "ensure_upstream_remote",
    "delete_ref",
    "undo_first_commit",
    "do_merge_commits_exist_after_commit",
    "get_last_fetched",
    "get_remote_head",
    "update_remote_head",
    "get_remote_url",
    "get_repository_type",
    "is_merge_head_set",
    "is_squash_msg_set",
    "is_cherry_pick_head_found",
    "list_submodules",
    "reset_submodule_paths",
    "get_upstream_ref_for_ref",
    "get_upstream_ref_for_local_branch_ref",
    "get_current_upstream_ref",
    "get_current_upstream_remote_name",
    "move_item_to_trash",
    "unstage_all_files",
    "escape_git_special_characters",
    "append_ignore_file",
    "get_partial_blob_contents",
    "add_global_config_value_if_missing",
    "add_conflicted_file",
    "checkout_conflicted_file",
    "remove_conflicted_file",
    "fill_credential",
    "approve_credential",
    "reject_credential",
    "update_ref",
    "get_global_config_value",
    "set_global_config_value",
    "remove_global_config_value",
    "get_global_boolean_config_value",
    "get_branch_ahead_behind",
    "get_commits_in_range",
    "rev_range_inclusive",
    "rev_symmetric_difference",
    "get_stashed_files",
    "get_trailer_separator_characters",
    "is_config_file_lock_error",
    "parse_config_lock_file_path_from_error",
    "env_for_proxy",
    "git_rebase_arguments",
    "env_for_authentication",
    "env_for_remote_operation",
    "get_fallback_url_for_proxy_resolve",
    "get_partial_blob_contents_catch_path_not_in_ref",
    "parse_commit_sha",
    "get_description_for_error",
    "is_auth_failure_error",
    "classify_git_error",
    "is_co_authored_by_trailer",
    "get_git_description",
    "write_git_description",
]


def test_all_git_ops_exported() -> None:
    for name in REQUIRED_GIT_FUNCS:
        assert hasattr(git_ops, name), name
        assert callable(getattr(git_ops, name))


def test_all_popups_have_handlers() -> None:
    # present_popup mapping must mention every production popup
    import inspect

    src = inspect.getsource(dialogs.present_popup)
    missing = []
    skip = {
        # macOS-only in upstream
        PopupType.UNTRUSTED_CERTIFICATE,
    }
    for popup in PopupType:
        if popup in skip:
            continue
        if popup.value not in src and popup.name not in src and f"PopupType.{popup.name}" not in src:
            missing.append(popup)
    assert missing == [], f"dialogs missing {missing}"


def test_preferences_tabs() -> None:
    assert list(PreferencesTab) == [
        PreferencesTab.ACCOUNTS,
        PreferencesTab.INTEGRATIONS,
        PreferencesTab.GIT,
        PreferencesTab.APPEARANCE,
        PreferencesTab.NOTIFICATIONS,
        PreferencesTab.PROMPTS,
        PreferencesTab.ADVANCED,
        PreferencesTab.ACCESSIBILITY,
    ]


def test_repository_settings_tabs() -> None:
    assert {t.value for t in RepositorySettingsTab} == {
        "Remote",
        "IgnoredFiles",
        "GitConfig",
        "ForkSettings",
    }


def test_banners_defined() -> None:
    assert BannerType.SUCCESSFUL_MERGE in BannerType
    assert BannerType.REBASE_CONFLICTS_FOUND in BannerType
    assert BannerType.OPEN_THANK_YOU_CARD in BannerType


def test_window_actions_cover_menus() -> None:
    src = open(MainWindow.__init__.__code__.co_filename, encoding="utf-8").read()
    from github_desktop.ui import stash, history, diff_view

    src += open(stash.__file__, encoding="utf-8").read()
    src += open(history.__file__, encoding="utf-8").read()
    src += open(diff_view.__file__, encoding="utf-8").read()
    from github_desktop.ui import dialogs as dialogs_mod, tutorial, checks
    from github_desktop.github import ci_checks, repo_rules
    from github_desktop.ui import multi_commit

    src += open(dialogs_mod.__file__, encoding="utf-8").read()
    src += open(tutorial.__file__, encoding="utf-8").read()
    src += open(checks.__file__, encoding="utf-8").read()
    src += open(ci_checks.__file__, encoding="utf-8").read()
    src += open(multi_commit.__file__, encoding="utf-8").read()
    src += open(repo_rules.__file__, encoding="utf-8").read()
    from github_desktop import thank_you, custom_integration
    from github_desktop.git import progress as git_progress

    src += open(thank_you.__file__, encoding="utf-8").read()
    src += open(custom_integration.__file__, encoding="utf-8").read()
    src += open(git_progress.__file__, encoding="utf-8").read()
    src += open(git_ops.__file__, encoding="utf-8").read()
    from github_desktop.git import diff as git_diff_mod

    src += open(git_diff_mod.__file__, encoding="utf-8").read()
    from github_desktop.git import askpass as git_askpass
    from github_desktop.git import credential_helper as git_cred_helper
    from github_desktop import store as store_mod, models as models_mod

    src += open(git_askpass.__file__, encoding="utf-8").read()
    src += open(git_cred_helper.__file__, encoding="utf-8").read()
    src += open(store_mod.__file__, encoding="utf-8").read()
    src += open(models_mod.__file__, encoding="utf-8").read()
    from github_desktop import api_cache as api_cache_mod

    src += open(api_cache_mod.__file__, encoding="utf-8").read()
    from github_desktop import api_repositories as api_repositories_mod

    src += open(api_repositories_mod.__file__, encoding="utf-8").read()
    from github_desktop import push_pull, commit_dnd
    from github_desktop.ui import css as css_mod

    src += open(push_pull.__file__, encoding="utf-8").read()
    src += open(commit_dnd.__file__, encoding="utf-8").read()
    src += open(css_mod.__file__, encoding="utf-8").read()
    from github_desktop.ui import application as app_mod
    from github_desktop.github import api as api_mod

    src += open(app_mod.__file__, encoding="utf-8").read()
    src += open(api_mod.__file__, encoding="utf-8").read()
    from github_desktop import create_repo as create_repo_mod

    src += open(create_repo_mod.__file__, encoding="utf-8").read()
    from github_desktop import clone_groups as clone_groups_mod
    from github_desktop.ui import branches as branches_mod

    src += open(clone_groups_mod.__file__, encoding="utf-8").read()
    src += open(branches_mod.__file__, encoding="utf-8").read()
    from github_desktop.ui import author_input as author_input_mod
    from github_desktop.ui import autocompletion as autocompletion_mod
    from github_desktop.github import ci_checks as ci_checks_mod

    src += open(author_input_mod.__file__, encoding="utf-8").read()
    src += open(autocompletion_mod.__file__, encoding="utf-8").read()
    src += open(ci_checks_mod.__file__, encoding="utf-8").read()
    from github_desktop import filter_changes as filter_changes_mod

    src += open(filter_changes_mod.__file__, encoding="utf-8").read()
    from github_desktop.ui import markdown as markdown_mod

    src += open(markdown_mod.__file__, encoding="utf-8").read()
    from github_desktop.git import runner as git_runner_mod
    from github_desktop.github import notifications as notifications_mod

    src += open(git_runner_mod.__file__, encoding="utf-8").read()
    src += open(notifications_mod.__file__, encoding="utf-8").read()
    from github_desktop import create_branch as create_branch_mod, email as email_mod, errors as errors_mod

    src += open(create_branch_mod.__file__, encoding="utf-8").read()
    src += open(email_mod.__file__, encoding="utf-8").read()
    src += open(errors_mod.__file__, encoding="utf-8").read()
    from github_desktop import editors as editors_mod
    from github_desktop.ui import dds as dds_mod

    src += open(editors_mod.__file__, encoding="utf-8").read()
    src += open(dds_mod.__file__, encoding="utf-8").read()
    from github_desktop import shells as shells_mod, notifications as notifications_mod_os

    src += open(shells_mod.__file__, encoding="utf-8").read()
    src += open(notifications_mod_os.__file__, encoding="utf-8").read()
    from github_desktop import changed_range as changed_range_mod, group_repositories as group_repos_mod, avatars as avatars_mod
    from github_desktop.github import push_control as push_control_mod

    src += open(changed_range_mod.__file__, encoding="utf-8").read()
    src += open(group_repos_mod.__file__, encoding="utf-8").read()
    src += open(avatars_mod.__file__, encoding="utf-8").read()
    src += open(push_control_mod.__file__, encoding="utf-8").read()
    from github_desktop import remote_parsing as remote_parsing_mod, settings as settings_mod

    src += open(remote_parsing_mod.__file__, encoding="utf-8").read()
    src += open(settings_mod.__file__, encoding="utf-8").read()
    from github_desktop import linux as linux_mod, text_tokens as text_tokens_mod
    from github_desktop.ui import menus as menus_mod

    src += open(linux_mod.__file__, encoding="utf-8").read()
    src += open(text_tokens_mod.__file__, encoding="utf-8").read()
    src += open(menus_mod.__file__, encoding="utf-8").read()
    from github_desktop import parse_pac as parse_pac_mod, linux_proxy as linux_proxy_mod, offset_from as offset_from_mod
    from github_desktop import (
        popup_manager as popup_manager_mod,
        truncate as truncate_mod,
        large_files as large_files_mod,
        infer_last_push as infer_last_push_mod,
        pull_request_matching as pr_matching_mod,
        get_file_hash as get_file_hash_mod,
        ssh_credentials as ssh_credentials_mod,
        enterprise as enterprise_mod,
        fuzzy_find as fuzzy_find_mod,
        remove_remote_prefix as remove_remote_prefix_mod,
        find_default_remote as find_default_remote_mod,
        find_default_branch as find_default_branch_mod,
        find_branch_name as find_branch_name_mod,
        tags_to_push as tags_to_push_mod,
        commit_url as commit_url_mod,
        find_account as find_account_mod,
        endpoint_capabilities as endpoint_capabilities_mod,
        git_error_context as git_error_context_mod,
        get_account as get_account_mod,
        features as features_mod,
        format_date as format_date_mod,
        directory_exists as directory_exists_mod,
        clamp as clamp_mod,
        http_status as http_status_mod,
        feature_flag as feature_flag_mod,
        secrets as secrets_mod,
        auth as auth_mod,
        desktop_fake_repository as desktop_fake_repo_mod,
        file_system as file_system_mod,
        path as path_mod,
        fatal_error as fatal_error_mod,
        compare as compare_mod,
        format_relative as format_relative_mod,
        generic_git_auth as generic_git_auth_mod,
        open_file as open_file_mod,
        format_commit_message as format_commit_message_mod,
        enum as enum_mod,
        local_storage as local_storage_mod,
        welcome as welcome_mod,
        tip as tip_mod,
        find_upstream_remote as find_upstream_remote_mod,
        tutorial_assessor as tutorial_assessor_mod,
        regex as regex_mod,
        errno_exception as errno_exception_mod,
        stats as stats_mod,
        changelog as changelog_mod,
        exception_reporting as exception_reporting_mod,
    )
    from github_desktop.git import delimiter as git_delimiter_mod

    src += open(parse_pac_mod.__file__, encoding="utf-8").read()
    src += open(linux_proxy_mod.__file__, encoding="utf-8").read()
    src += open(offset_from_mod.__file__, encoding="utf-8").read()
    src += open(popup_manager_mod.__file__, encoding="utf-8").read()
    src += open(truncate_mod.__file__, encoding="utf-8").read()
    src += open(large_files_mod.__file__, encoding="utf-8").read()
    src += open(infer_last_push_mod.__file__, encoding="utf-8").read()
    src += open(pr_matching_mod.__file__, encoding="utf-8").read()
    src += open(get_file_hash_mod.__file__, encoding="utf-8").read()
    src += open(ssh_credentials_mod.__file__, encoding="utf-8").read()
    src += open(enterprise_mod.__file__, encoding="utf-8").read()
    src += open(fuzzy_find_mod.__file__, encoding="utf-8").read()
    src += open(remove_remote_prefix_mod.__file__, encoding="utf-8").read()
    src += open(find_default_remote_mod.__file__, encoding="utf-8").read()
    src += open(find_default_branch_mod.__file__, encoding="utf-8").read()
    src += open(find_branch_name_mod.__file__, encoding="utf-8").read()
    src += open(tags_to_push_mod.__file__, encoding="utf-8").read()
    src += open(commit_url_mod.__file__, encoding="utf-8").read()
    src += open(find_account_mod.__file__, encoding="utf-8").read()
    src += open(endpoint_capabilities_mod.__file__, encoding="utf-8").read()
    src += open(git_delimiter_mod.__file__, encoding="utf-8").read()
    src += open(git_error_context_mod.__file__, encoding="utf-8").read()
    src += open(get_account_mod.__file__, encoding="utf-8").read()
    src += open(features_mod.__file__, encoding="utf-8").read()
    src += open(format_date_mod.__file__, encoding="utf-8").read()
    src += open(directory_exists_mod.__file__, encoding="utf-8").read()
    src += open(clamp_mod.__file__, encoding="utf-8").read()
    src += open(http_status_mod.__file__, encoding="utf-8").read()
    src += open(feature_flag_mod.__file__, encoding="utf-8").read()
    src += open(secrets_mod.__file__, encoding="utf-8").read()
    src += open(auth_mod.__file__, encoding="utf-8").read()
    src += open(desktop_fake_repo_mod.__file__, encoding="utf-8").read()
    src += open(file_system_mod.__file__, encoding="utf-8").read()
    src += open(path_mod.__file__, encoding="utf-8").read()
    src += open(fatal_error_mod.__file__, encoding="utf-8").read()
    src += open(compare_mod.__file__, encoding="utf-8").read()
    src += open(format_relative_mod.__file__, encoding="utf-8").read()
    src += open(generic_git_auth_mod.__file__, encoding="utf-8").read()
    src += open(open_file_mod.__file__, encoding="utf-8").read()
    src += open(format_commit_message_mod.__file__, encoding="utf-8").read()
    src += open(enum_mod.__file__, encoding="utf-8").read()
    src += open(local_storage_mod.__file__, encoding="utf-8").read()
    src += open(welcome_mod.__file__, encoding="utf-8").read()
    src += open(tip_mod.__file__, encoding="utf-8").read()
    src += open(find_upstream_remote_mod.__file__, encoding="utf-8").read()
    src += open(tutorial_assessor_mod.__file__, encoding="utf-8").read()
    src += open(regex_mod.__file__, encoding="utf-8").read()
    src += open(errno_exception_mod.__file__, encoding="utf-8").read()
    src += open(stats_mod.__file__, encoding="utf-8").read()
    src += open(changelog_mod.__file__, encoding="utf-8").read()
    src += open(exception_reporting_mod.__file__, encoding="utf-8").read()
    for action in [
        "new-repository",
        "clone-repository",
        "preferences",
        "push",
        "pull",
        "fetch",
        "create-branch",
        "merge-branch",
        "rebase-branch",
        "open-pull-request",
        "generate-commit-message",
        "open-in-shell",
        "open-external-editor",
        "create-tag",
        "stash-all",
        "install-cli",
        "toggle-changes-filter",
        "zoom-in",
        "update-from-default",
        "release-notes",
        "edit-undo",
        "increase-resizable",
        "toggle-fullscreen",
    ]:
        assert action in src
    for phrase in [
        "Discard changes",
        "Copy SHA",
        "Side-by-side",
        "Cherry-pick",
        "Ignore file",
        "Install command line tool",
        "Zoom in",
        "Modified",
        "Stashed changes",
        "Search commits",
        "Can't find this repository",
        "Open in default program",
        "Switch to pull request",
        "Release notes",
        "Get started",
        "Exit tutorial",
        "Re-run failed checks",
        "All checks have passed",
        "View logs",
        "GitHub Enterprise",
        "line endings",
        "Create a merge commit",
        "Checking for ability to merge automatically",
        "View conflicts",
        "Confirm abort",
        "will require force push",
        "Do not show this message again",
        "repository rules",
        "Open with default program",
        "Completeness indicator",
        "protected branch",
        "I understand",
        "Copilot is powered by AI",
        "Able to merge automatically",
        "Stop amending",
        "most recent commit",
        "Undo commit?",
        "hidden changes",
        "Update existing Git LFS filters",
        "Edit global Git config",
        "Unknown co-authors",
        "Cloning…",
        "Thanks so much for all your hard work",
        "You contributed:",
        "Configure custom editor",
        "%TARGET_PATH%",
        "leftover conflict marker",
        "Leftover conflict markers remain",
        "Open Your Card",
        "Explore projects on GitHub",
        "You're done!",
        "Explore GitHub",
        "The branch also exists on the remote",
        "Yes, delete this branch on the remote",
        "This branch may have an open pull request associated with it.",
        "1 tag",
        "github-desktop-",
        "GIT_ASKPASS",
        "The authenticity of host",
        "Publish your repository to GitHub",
        "Commit anyway",
        "View stash",
        "Re-authorization required",
        "versioning-large-files",
        "Contribute to the parent repository",
        "Stash all changes?",
        "placeholder_id",
        "discarded permanently",
        "Force push",
        "detached HEAD",
        "Selecting lines is disabled when hiding whitespace changes",
        "Return to in progress tutorial",
        "Copy relative file path",
        "This email address doesn't match your GitHub account",
        "with rebase",
        "rebase.backend=merge",
        "leave the tutorial",
        "Last fetched",
        "Never fetched",
        "Allow me to expose this secret",
        "It's a false positive",
        "Unable to squash",
        "Unable to reorder",
        "commit-drop-squash",
        "underline-links",
        "Reverting first commit",
        "pan-down-symbolic",
        "Showing changes from",
        "unreachable",
        "commit-highlight",
        "edit-undo",
        "Hide stashed changes",
        "View pull request on GitHub",
        "Force push…",
        "Preview pull request",
        "BACKGROUND_FETCH_MINIMUM_INTERVAL",
        "Expand active resizable",
        "repo-changes-dot",
        "PullRequestSuggestedNextAction",
        "BackgroundFetcher",
        "get_fetch_poll_interval",
        "Archived",
        "Private repository",
        "Initialize this repository with a README",
        "Git ignore",
        "Will be created as",
        "Learn about submodules.",
        "getGitIgnoreNames",
        "writeGitIgnore",
        "github/gitignore",
        "getLicenses",
        "writeLicense",
        "choosealicense",
        "mentionables/users",
        "updateRemoteHEAD",
        "Cancel clone",
        "getRepositoryType",
        "listSubmodules",
        "abort_clone",
        "This directory does not appear to be a Git repository",
        "Bare repositories are not currently supported",
        "add an exception for this directory",
        "Changes can be restored by retrieving them from the Trash",
        "Discarded changes will be unrecoverable",
        "moveItemToTrash",
        "Keep this code private",
        "Create without pushing",
        "Create as draft",
        "Your repositories",
        "Clone failed",
        "Would you like to retry cloning",
        "Stash changes and continue",
        "Delete tag",
        "unstageAllFiles",
        "escapeGitSpecialCharacters",
        "getPartialBlobContents",
        "addGlobalConfigValueIfMissing",
        "popStashEntry",
        "Copy paths",
        "startCherryPickWithPullRequest",
        "openCreatePullRequestInBrowser",
        "You're already signed in",
        "Use my global Git config",
        "Use a local Git config",
        "For this repository I wish to",
        "Publish this repository to GitHub",
        "subscribeToCommitStatus",
        "AuthorInput",
        "AuthorHandle",
        "Filter branches",
        "Use the added file",
        "Do not include this file",
        "getLabelForManualResolutionOption",
        "CIStatus",
        "ExistingAccountWarning",
        "aheadBehindStore",
        "Co-Author",
        "Newer commits on remote",
        "Confirm committing conflicted files",
        "Yes, commit files",
        "Invalidated account token",
        "Continue in browser",
        "Are you sure you want to discard these stashed changes?",
        "overwrite your existing stash",
        "create a detached HEAD",
        "Learn more about gitignore files",
        "intentionally untracked files",
        "No description provided.",
        "PullRequestQuickView",
        "GitConfigUserForm",
        "Open a pull request",
        "prRecentBaseBranches",
        "Resolve all conflicts before continuing",
        "Untracked files will be excluded",
        "Empty commit message",
        "This commit has not been pushed to the remote repository",
        "image-diff-swipe",
        "unpushed-indicator",
        "tag-indicator",
        "addConflictedFile",
        "fillCredential",
        "updateRef",
        "getGlobalConfigValue",
        "revSymmetricDifference",
        "getCommitsInRange",
        "getBranchAheadBehind",
        "added lines",
        "Sorry, I can't find that remote branch.",
        "You can only open pull requests against remote branches.",
        "Sorry, I can't find that repository",
        "push-last-fetched",
        "isCommittingFileHiddenByFilter",
        "getNoResultsMessage",
        "Sorry, I can't find any changed files matching the following filters:",
        "isIncludedInCommit",
        "Included in commit",
        "SandboxedMarkdown",
        "Sign in to your GitHub.com account",
        "You're all set!",
        "Sorry, I can't find that pull request!",
        "generatedByCopilot",
        "getStashedFiles",
        "RepoRulesetsForBranchLink",
        "Can't preview .dds on Linux",
        "image-diff-difference",
        "OPERATOR_DIFFERENCE",
        "syncClockwise",
        "No open pull requests in",
        "View repository rulesets",
        "MentionFilter",
        "CommitMentionFilter",
        "getTrailerSeparatorCharacters",
        "There will be",
        "Unable to merge unrelated histories in this repository",
        "Sign into GitHub.com",
        "high-signal events",
        "Select Branch to Compare",
        "No branches to compare",
        "ConfigLockFileExists",
        "isConfigFileLockError",
        "envForProxy",
        "This pull request closes",
        "TeamMention",
        "gh-123",
        "Add GitHub Enterprise account",
        "getMergeOptions",
        "CloseKeywordFilter",
        "IssueMentionFilter",
        "getStartPoint",
        "--no-track",
        "gitRebaseArguments",
        "envForAuthentication",
        "envForRemoteOperation",
        "getPartialBlobContentsCatchPathNotInRef",
        "getFallbackUrlForProxyResolve",
        "Your commits will be wrongly attributed",
        "already exists on the remote",
        "The default branch in your repository",
        "Always available in the toolbar",
        "When a stash exists",
        "Publish your branch",
        "Learn more about commit signing",
        "create a fork",
        "switch branches",
        "GitEmailNotFoundWarning",
        "parseCommitSHA",
        "getDescriptionForError",
        "isAuthFailureError",
        "Authentication failed. Some common reasons include",
        "File > Options.",
        "This branch is protected from force-push operations.",
        "Unable to switch branches as there are working directory changes",
        "GIT_LFS_PROGRESS",
        "--recurse-submodules=on-demand",
        "Unable to open external editor",
        "Unable to open shell",
        "The diff is too large to be displayed by default",
        "is_co_authored_by_trailer",
        "Show whitespace changes?",
        "Copy the full",
        "create_lfs_progress_file",
        "lookup_preferred_email",
        "Open options",
        "Download {SUGGESTED_EXTERNAL_EDITOR}",
        "SUGGESTED_EXTERNAL_EDITOR",
        "checkoutBranch",
        "Show diff",
        "pixbuf_from_dds",
        "diff-add-inner",
        "diff-delete-inner",
        "relativeChanges",
        "getDiffTokens",
        "push_control",
        "is_branch_pushable",
        "fetchCombinedRefStatus",
        "No newline at end of file",
        "Unable to locate Git",
        "Install Git",
        "Open without Git",
        "desktop/avatar-token",
        "This email address is disallowed",
        "group_repositories",
        "recent_repository_ids",
        "current_branch_protected",
        "emitTokenInvalidated",
        "useExternalCredentialHelper",
        "Diff options",
        "hideWhitespaceInHistoryDiff",
        "hideWhitespaceInPullRequestDiff",
        "isGitHubHost",
        "create_pull_request_from_preview",
        "Hide whitespace changes",
        "prBaseBranches",
        "beginBrowserBasedSignIn",
        "ConfirmOverwriteStash",
        "Initialize Git LFS",
        "installLFSHooks",
        "_abortSquashMerge",
        "createSquashMergeCommit",
        "isGeneratingCommitMessage",
        "isCommitting",
        "filesNotTrackedByLFS",
        "fetchRepositoryCloneInfo",
        "Creating repository on",
        "Welcome to GitHub Desktop!",
        "Write your name on line 6",
        "Generating commit details",
        "Show More locations",
        "Start tutorial",
        "Not now",
        "MaxTagNameLength",
        "isUncommittableSubmodule",
        "isPartiallyCommittableSubmodule",
        "warp-terminal",
        "ghostty",
        "com.visualstudio.code",
        "allPopups",
        "updateCheckoutProgress",
        "RepoRulesetLink",
        "grant permission",
        "Notifications Settings",
        "Previous tags",
        "You are not able to cherry-pick from and to the same branch",
        "new-branch-drop",
        "RetryActionType",
        "_checkForUncommittedChanges",
        "insufficientGitHubRepoPermissions",
        "Remember passphrase",
        "performRetry",
        "CloningRepositoryView",
        "accessibility-banner-dismissed",
        "link underlines and diff check marks",
        "PublishTab",
        "Ask me where I want the changes to go",
        "Always bring my changes to my new branch",
        "Always stash and leave my changes on the current branch",
        "creating the fork manually on GitHub",
        "isCredentialHelperSignIn",
        "withTrampolineEnv",
        "ConfigureGitUser",
        "credential.helper=desktop",
        "createCredentialHelperTrampolineHandler",
        "x-github-request-id",
        "GIT_CONFIG_PARAMETERS",
        "GIT_USER_AGENT",
        "create-fork",
        "Creating fork…",
        "deleteMostRecentSSHCredential",
        "setMostRecentSSHCredential",
        "License and Open Source Notices",
        "Terms and Conditions",
        "Responsible use of Copilot in GitHub Desktop",
        "Press F11 to exit fullscreen",
        "FullScreenInfo",
        "ZoomInfo",
        "Toggle full screen",
        "Sorry, I can't find that branch",
        "Do you want to create a new branch instead?",
        "to quickly create a new branch from anywhere within the app",
        "to quickly add a local repository",
        "to clone from anywhere within the app",
        "drag & drop an existing",
        "This binary file has changed",
        "Open file in external program.",
        "Name is invalid, it consists only of disallowed characters.",
        "gitAuthorNameIsValid",
        "HighlightText",
        "window-zoom-info",
        "toast-notification-container",
        "This operating system is no longer supported",
        "isWebFlowCommitter",
        "wrapRichTextCommitMessage",
        "getOldPathOrDefault",
        "getUniqueCoauthorsAsAuthors",
        "getSquashedCommitDescription",
        "bodyNoCoAuthors",
        "convertToFlatpakPath",
        "isFlatpakBuild",
        "Show in your File Manager",
        "Copy file path",
        "Copy relative paths",
        "Copy repo name",
        "Copy repo path",
        "Remove alias",
        "MaxSummaryLength",
        "Squash {count} Commits",
        "Unable to display diff when multiple non-consecutive selected.",
        "Also move this repository to",
        "Show logs in your File Manager",
        "Successfully copied",
        "File does not exist on disk",
        "Looks like there are no repositories for",
        "Sorry, I can't find any repository matching",
        "No size difference",
        "View on GitHub Enterprise",
        "TrashNameLabel",
        "mapStatus",
        "Successfully merged into",
        "Successfully rebased",
        "Successfully squashed",
        "non_contiguous_selection",
        "W: {width}px",
        "Expand active resizable",
        "Contract active resizable",
        "Squash and merge into current branch",
        "Show User Guides",
        "Hide changes filter",
        "No files match your current filters",
        "Clear filters",
        "Use Git Credential Manager",
        "Help GitHub Desktop improve by submitting usage stats",
        "Are you sure you want to continue connecting?",
        "Successfully reordered",
        "Resolve conflicts and commit to merge into",
        "https://gh.io/gcm",
        "Ignore {len(paths)} selected files (add to .gitignore)",
        "Are you sure you want to force push?",
        "I'm sure",
        "Commit message override",
        "will be overridden by the generated commit message",
        "Learn more about unreachable commits.",
        "Great commit summaries contain fewer than 50 characters",
        "Commit reachability",
        "A force push will rewrite history on",
        "refresh_issues",
        "DefaultMaxHits",
        "Welcome to GitHub Desktop",
        "Create your free account.",
        "Learn more about user metrics.",
        "You have changes on this branch. What would you like to do with them?",
        "Leave my changes on",
        "Bring my changes to",
        "Your current stash will be overwritten by creating a new stash",
        "Undo is disabled while the repository is being updated",
        "commit_summary_placeholder",
        "tokens_as_markup",
        "delete_oauth_token",
        "Create {name}",
        "Discard added line",
        "Discard removed line",
        "Discard modified line",
        "Use ↑ ↓ to choose a new location.",
        "Press ⏎ to confirm.",
        "Use the Up and Down arrow keys to choose a new location for the selected commit",
        "Press Enter to insert the selected commit",
        "find_interactive_diff_range",
        "_start_gutter_selection",
        "temporary_selection",
        "keyboard_reorder_intro_message",
        "desktop_copilot_generate_commit_message",
        "enable_commit_message_generation",
        "secret-scanning/push-protection-bypasses",
        "github-desktop-commit-message-generation",
        "Show check marks in the diff",
        "Show commit length warning",
        "Overriding commit message with generated message",
        "This is an example link",
        "Files must be selected to generate a commit message",
        "isCopilotDesktopEnabled",
        "fetchPRWorkflowRunsByBranchName",
        "getLatestCheckRunsById",
        "fetchAllRepoRulesets",
        "updateRemoteUrl",
        "If-None-Match",
        "fetchUpdatedPullRequests",
        "manuallySetChecksToPending",
        "PullRequestInterval",
        "fetchIssueComment",
        "fetchPullRequestReview",
        "MaxFetchFrequency",
        "hunk-handle",
        "isOnlyOneCheckInRow",
        "parsePACString",
        "org.gnome.system.proxy",
        "kioslaverc",
        "ignore-hosts",
        "--action=default:Open",
        "getGitDescription",
        "DefaultGitDescription",
        "MouseScroller",
        "resolveGitProxy",
        "Lines ",
        "getNextPagePathFromLink",
        "getNextPagePathWithIncreasingPageSize",
        "fetchAllOpenPullRequests",
        "fetchWorkflowRunJobs",
        "fetchPullRequestReviews",
        "fetchIssueComments",
        "parseCarriageReturn",
        "offsetFromNow",
        "urlWithQueryString",
        "getLatestPRWorkflowRunsLogsForCheckRun",
        "PopupManager",
        "TooManyPopups",
        "truncateWithEllipsis",
        "getLargeFilePaths",
        "inferLastPushForRepository",
        "isValidNotificationPullRequestReview",
        "matchGitHubRepository",
        "matchExistingRepository",
        "urlsMatch",
        "parseRepositoryIdentifier",
        "ReceiveLimit",
        "findAssociatedPullRequest",
        "isPullRequestAssociatedWithBranch",
        "getFileHash",
        "getSSHCredentialStoreKey",
        "SSH key passphrases",
        "SSH user password",
        "validateURL",
        "InvalidProtocolErrorName",
        "InvalidURLErrorName",
        "Only https is supported",
        "findDefaultBranch",
        "findRemoteBranchName",
        "removeRemotePrefix",
        "storeTagsToPush",
        "findDefaultRemote",
        "githubAssetVideoRegex",
        "isEmptyOrWhitespace",
        "tags-to-push-",
        "VideoLinkFilter",
        "fuzzaldrin-plus",
        "createCommitURL",
        "findAccountForRemoteURL",
        "Account.anonymous",
        "endpointSatisfies",
        "assumedGHESVersion",
        "supportsRepoRules",
        "supportsRerunningChecks",
        "supportsAvatarsAPI",
        "createLogParser",
        "createForEachRefParser",
        "splitBuffer",
        "maxSize: 2500",
        "GitErrorContext",
        "ErrorWithMetadata",
        "Failed creating repository",
        "Failed to push",
        "getAccountForEndpoint",
        "getAccountForRepository",
        "IssueLinkFilter",
        "CommitMentionLinkFilter",
        "subarray(0, 100 * 1024)",
        "parseRawLogWithNumstat",
        "getChangesFiles",
        "isGitOnPath",
        "findGitOnPath",
        "getOS",
        "getDefaultDir",
        "last-clone-location",
        "shouldRenderApplicationMenu",
        "features/should-render-application-menu",
        "createTailStream",
        "createTerminalStream",
        "isRawMessage",
        "formatDate",
        "Invalid date",
        "dateStyle",
        "directoryExists",
        "clamp",
        "HttpStatusCode",
        "NotModified",
        "genericGitAuth/username/",
        "enableRecurseSubmodulesFlag",
        "enableResetToCommit",
        "enableCheckoutCommit",
        "TERM",
        "getKeyForEndpoint",
        "getKeyForAccount",
        "GitHub Desktop Dev",
        "DesktopFakeRepository",
        "getMediaType",
        "image/jpg",
        "image/vnd-ms.dds",
        "getTempFilePath",
        "readPartialFile",
        "resolveWithin",
        "encodePathAsUrl",
        "fatalError",
        "forceUnwrap",
        "assertNever",
        "assertNonNullable",
        "caseInsensitiveCompare",
        "formatRelative",
        "numeric: 'auto'",
        "isQuotaExceededError",
        "friendlyEndpointName",
        "no-external-program",
        "Unable to open file",
        "createLFSProgressFile",
        "getGenericUsername",
        "setGenericCredential",
        "formatCommitMessage",
        "mergeTrailers",
        "hasConflictedFiles",
        "getUnmergedFiles",
        "getUntrackedFiles",
        "getResolvedFiles",
        "getUnmergedStatusEntryDescription",
        "isConflictedFile",
        "No conflicts remaining",
        "tryGetAheadBehind",
        "MaxConcurrent = 1",
        "getFormattedCheckRunDuration",
        "getFormattedCheckRunLongDuration",
        "getCheckDurationInMilliseconds",
        "getBoolean",
        "setBoolean",
        "getNumber",
        "getFloatNumber",
        "getStringArray",
        "setStringArray",
        "getNumberArray",
        "getEnum",
        "getObject",
        "setObject",
        "parseEnumValue",
        "NumberArrayDelimiter",
        "revealInFileManager",
        "formatGitIgnoreContents",
        "readGitIgnoreAtRoot",
        "saveGitIgnore",
        "findContributionTargetDefaultBranch",
        "isRepositoryWithGitHubRepository",
        "isRepositoryWithForkedGitHubRepository",
        "calculateConflicts",
        "AuthenticationErrors",
        "getCurrentUpstreamRef",
        "getCurrentUpstreamRemoteName",
        "git-trace",
        "core.autocrlf",
        "core.safecrlf",
        "1 conflict",
        "hasShownWelcomeFlow",
        "markWelcomeFlowComplete",
        "has-shown-welcome-flow",
        "getTipSha",
        "tipEquals",
        "findUpstreamRemote",
        "UpstreamRemoteName",
        "tabSizeDefault",
        "tab-size",
        "use-custom-editor",
        "use-custom-shell",
        "diff-check-marks-visible",
        "show-changes-filter",
        "commit-spellcheck-enabled",
        "enable-repository-indicators",
        "show-commit-length-warning",
        "nameOf",
        "getGitHubHtmlUrl",
        "getNonForkGitHubRepository",
        "assertIsRepositoryWithGitHubRepository",
        "Repository must be GitHub repository",
        "getAuthorIdentity",
        "sanitizedRefName",
        "parseIdentity",
        "Will be created as",
        "Choose a new alias for the repository",
        "getForkContributionTarget",
        "isForkedRepositoryContributingToParent",
        "getUpstreamRefForLocalBranchRef",
        "tutorial-install-editor-skipped",
        "tutorial-pull-request-step-complete",
        "tutorial-paused",
        "OnboardingTutorialAssessor",
        "skipPickEditor",
        "markPullRequestTutorialStepAsComplete",
        "markTutorialCompletionAsAnnounced",
        "onNewTutorialRepository",
        "isValidTutorialStep",
        "orderedTutorialSteps",
        "AllDone",
        "Announced",
        "getFileFromExceedsError",
        "Files that exceed the limit",
        "https://gh.io/lfs",
        "Quota exceeded",
        "File size limit exceeded",
        "Upgrade to increase your limit.",
        "https://github.com/features/copilot/plans",
        "isErrnoException",
        "Failed to execute",
        "coerceToString",
        "coerceToBuffer",
        "isMaxBufferExceededError",
        "ERR_CHILD_PROCESS_STDIO_MAXBUFFER",
        "expectedErrors",
        "isGitError",
        "BadRevision",
        "parseCherryPickResult",
        "BranchDeletionFailed",
        "ConflictModifyDeletedInBranch",
        "ConfigLockFileAlreadyExists",
        "ensureRelativePath",
        ":(top,literal)",
        "getCommitDiff",
        "diffFromRawDiffOutput",
        "--patch-with-raw",
        "Can't create partial commit",
        "VideoTagFilter",
        "the stash entry is kept in case you need it again",
        "getBlobContents",
        "getPartialBlobContentsCatchPathNotInRef",
        "fetchTagsToPush",
        "getBranchesDifferingFromUpstream",
        "github-api-cache.json",
        "getLatestUpdatedAt",
        "IssuesDatabase",
        "tryUpdateEndpointVersionFromResponse",
        "rejectOnError",
        "--unset-all",
        "removeRemote",
        "Loading repositories…",
        "streamUserRepositories",
        "ApiRepositoriesStore",
        "loadRepositories",
        "last-daily-stats-report",
        "stats-opt-out",
        "has-sent-stats-opt-in-ping",
        "StatsEndpoint",
        "SamplesURL",
        "reportStats",
        "getHasOptedOutOfStats",
        "getRendererGUID",
        "stats-guid",
        "getChangeLog",
        "getThankYouByUser",
        "ErrorEndpoint",
        "unrecoverable error",
        "getArchitecture",
        "SendStatsInterval",
        "accountEquals",
        "Let's get started!",
        "Add a repository to GitHub Desktop to start collaborating",
        "Unable to create repository for organization",
        "Unable to publish repository",
        "Filter your repositories",
        "Loading repositories from",
        "Refresh the list of repositories",
        "fetchOrgs",
        "fetchIssues",
        "createRepository",
        "IAccountRepositories",
        "Unable to create push protection bypass",
        "Try again at",
        "fetchProtectedBranches",
        "fetchUser",
        "forkRepository",
        "fetchPullRequestComments",
        "Failed to load avatar token",
        "[_createPushProtectionBypass]",
        "[fetchCheckSuite]",
        "[fetchRepoRulesForBranch]",
        "[fetchAllRepoRulesets]",
        "[fetchRepoRuleset]",
        "isRulesetsNotEnabledError",
        "getStealthEmailForUser",
        "getLegacyStealthEmailForUser",
        "fetchRepository",
        "getPermissionsString",
        "fetchAccount",
        "fetchEmails",
        "rerequestCheckSuite",
        "rerunFailedJobs",
        "rerunJob",
        "Failed fetching check runs for ref",
        "getFetchPollInterval",
        "requestOAuthToken",
        "Error refreshing account",
        "getDiffChangesCommitMessage",
        "[fetchPushControl]",
        "[createDesktopStashEntry]",
        "[popStashEntry]",
        "isGitHubHost",
        "getImageDiff",
        "installGlobalLFSFilters",
        "parentCommitish",
        "continueRebase",
        "continueCherryPick",
        "continueRebaseSkipCurrentCommit",
        "continueCherryPickSkipCurrentCommit",
        "Checking mergeability",
        "discardChangesFromSelection",
        "_finishConflictedMerge",
        "no tracked changes to commit",
        "readRebaseHead",
        "parseRebaseResult",
        "couldn't find file",
        "pre-wrap",
        "break-all",
        "loadFilesForCurrentStashEntry",
        "_run_ui",
        "CreateBranchForCherryPick",
    ]:
        assert phrase in src
